// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjG3yh2PHkjXTFCVOXe3YkFdL7Y53swbQ',
    appId: '1:303882680944:web:d9d198c76b5635252112b5',
    messagingSenderId: '303882680944',
    projectId: 'reproductor-7bbc6',
    authDomain: 'reproductor-7bbc6.firebaseapp.com',
    storageBucket: 'reproductor-7bbc6.appspot.com',
    measurementId: 'G-7FB1ZWYFYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOpTQwQpyC8PqsO3Df7C6-ROeh_dbLuY',
    appId: '1:303882680944:android:e4d372d5577d40062112b5',
    messagingSenderId: '303882680944',
    projectId: 'reproductor-7bbc6',
    storageBucket: 'reproductor-7bbc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh62dxJJZyTgnayezSpd3AWi7uijzaEbQ',
    appId: '1:303882680944:ios:28ae78a574fe535d2112b5',
    messagingSenderId: '303882680944',
    projectId: 'reproductor-7bbc6',
    storageBucket: 'reproductor-7bbc6.appspot.com',
    iosBundleId: 'com.example.pryind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh62dxJJZyTgnayezSpd3AWi7uijzaEbQ',
    appId: '1:303882680944:ios:28ae78a574fe535d2112b5',
    messagingSenderId: '303882680944',
    projectId: 'reproductor-7bbc6',
    storageBucket: 'reproductor-7bbc6.appspot.com',
    iosBundleId: 'com.example.pryind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjG3yh2PHkjXTFCVOXe3YkFdL7Y53swbQ',
    appId: '1:303882680944:web:79d5e6a348ee35482112b5',
    messagingSenderId: '303882680944',
    projectId: 'reproductor-7bbc6',
    authDomain: 'reproductor-7bbc6.firebaseapp.com',
    storageBucket: 'reproductor-7bbc6.appspot.com',
    measurementId: 'G-HSJMTE2GF5',
  );
}
